#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sat Jun 15 18:11:08 2019

@author: shenzhengfei
"""

import fun_ware
import matplotlib.pyplot as plt


statsData,votesData,sideDic,statsWithVotesInfo = fun_ware.getDataWithVoteInfo()

firstEntropyDic,UltimaEntropyDic=fun_ware.voteEntropyComp(votesData)

vector = firstEntropyDic.values()

n, bins, patches = plt.hist(vector,bins=10,normed=0,facecolor='green',edgecolor='black',alpha=1,histtype='bar')

plt.xlabel("entropy")
plt.ylabel("number")